# Book settings
title: RxPy OpKit
author: GProtoZeroW
logo: ""
copyright: "2025"

# Force re-execution of notebooks on each build
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: rxpy_opkit.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/GProtoZeroW/rxpy_opkit
  branch: main

# Add GitHub buttons to your book
html:
  use_issues_button: true
  use_repository_button: true

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Launch button settings
launch_buttons:
  notebook_interface: jupyterlab
  binderhub_url: ""

# Parse and render settings
parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist

# Add MyST-NB
sphinx:
  extra_extensions:
    - sphinx.ext.autodoc
    - sphinx.ext.intersphinx
    - sphinx.ext.viewcode
    - sphinx.ext.napoleon
    - sphinx_togglebutton
    - sphinx_copybutton
    - sphinx_thebe
