# Book settings
title: ReactiveX for Python Learning Book
author: GProtoZeroW
logo: ""
copyright: "2024"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  allow_errors: false

# Define the paths to build
paths:
  # Path to the files that should be built relative to the book's root
  content: "." 
  # Path to external files that should be built as part of the book
  # but aren't in the TOC.
  external: "../"


# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/GProtoZeroW/rxpy_opkit  # Online location of your book
  path_to_book: notebooks  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links

# Add GitHub buttons to your book
html:
  use_issues_button: true
  use_repository_button: true
  extra_footer: |
    <div>
      <a href="https://reactivex.io/">ReactiveX</a>
    </div>
  extra_css:
    - css/custom.css

# Launch button settings
launch_buttons:
  notebook_interface: jupyterlab
  binderhub_url: ""

# Parse and render settings
parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist

# Add MyST-NB
sphinx:
  extra_extensions:
    - sphinx.ext.autodoc
    - sphinx.ext.intersphinx
    - sphinx.ext.viewcode
    - sphinx.ext.napoleon
    - sphinx_togglebutton
    - sphinx_copybutton
    - sphinx_thebe
    - sphinxcontrib.mermaid
